name: carspace
description: CarSpace - Because Your Parking Matters


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #google service dependencies
  firebase_auth: ^0.16.0
  google_maps_flutter: ^0.5.11
  google_sign_in: ^4.4.4
    #http client
  dio: ^3.0.9
  http: ^0.12.1
  http_parser: ^3.1.4
  mime: ^0.9.6+3
  chopper: ^3.0.2
  #local storage
  shared_preferences: ^0.5.7+1
  #visual elements and behaviours
  carousel_slider: ^2.0.0
  charts_flutter: ^0.9.0
  charts_common: ^0.9.0
  credit_card: ^0.1.6
  font_awesome_flutter: ^8.0.1
  flutter_circular_chart: ^0.1.0
  flutter_credit_card: ^0.1.1
  flutter_cupertino_date_picker: ^1.0.24
  share: 0.6.4+2
  flutter_staggered_grid_view: ^0.2.7
  flutter_sparkline: ^0.1.0
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  getflutter: ^1.0.7
  intro_slider: ^2.2.9
  image_picker: ^0.6.6+1
  numberpicker: ^1.2.0
  slider_button: ^0.5.0
  provider: 4.1.3+1
  flutter_bloc: 5.0.1
  equatable: ^1.0.3
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  build_runner:
  chopper_generator: ^3.0.4
  #terminal: flutter packages pub run build_runner build
  #terminal: flutter packages pub run build_runner watch
  json_serializable: ^3.3.0
  #terminal: flutter packages pub run build_runner build

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher_icon.png"

#run this command to update the launcher icon
#flutter pub run flutter_launcher_icons:main
#https://pub.dev/packages/flutter_launcher_icons

flutter_native_splash:
  image: assets/logo/splash_icon.png
  color: "1a237e"
  fill: true

#run this command to update the splash screen
#flutter pub pub run flutter_native_splash:create
#https://pub.dev/packages/flutter_native_splash

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/login_screen_assets/
    - assets/mapStyle.txt
    - assets/launcher_icon/

  fonts:
    - family: Champagne & Limousines
      fonts:
        - asset: assets/fonts/Champagne&Limousines-Italic.ttf
        - asset: assets/fonts/Champagne&Limousines-Bold-Italic.ttf
        - asset: assets/fonts/Champagne&Limousines-Bold.ttf
        - asset: assets/fonts/Champagne&Limousines.ttf